// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.9
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// c:\gamez\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:152

#ifndef _TAO_PIDL_MESSAGING_SYNCSCOPEC_ZRDBZY_H_
#define _TAO_PIDL_MESSAGING_SYNCSCOPEC_ZRDBZY_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "tao/TAO_Export.h"
#include "tao/Basic_Types.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 1 || TAO_BETA_VERSION != 9
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO TAO_Export

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\gamez\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:38

namespace Messaging
{

  // TAO_IDL - Generated from
  // c:\gamez\ace_wrappers\tao\tao_idl\be\be_visitor_typedef\typedef_ch.cpp:373

  typedef ::CORBA::Short SyncScope;
  typedef ::CORBA::Short_out SyncScope_out;

  // TAO_IDL - Generated from
  // c:\gamez\ace_wrappers\tao\tao_idl\be\be_visitor_constant\constant_ch.cpp:38

  const CORBA::Short SYNC_NONE = 0;

  // TAO_IDL - Generated from
  // c:\gamez\ace_wrappers\tao\tao_idl\be\be_visitor_constant\constant_ch.cpp:38

  const CORBA::Short SYNC_WITH_TRANSPORT = 1;

  // TAO_IDL - Generated from
  // c:\gamez\ace_wrappers\tao\tao_idl\be\be_visitor_constant\constant_ch.cpp:38

  const CORBA::Short SYNC_WITH_SERVER = 2;

  // TAO_IDL - Generated from
  // c:\gamez\ace_wrappers\tao\tao_idl\be\be_visitor_constant\constant_ch.cpp:38

  const CORBA::Short SYNC_WITH_TARGET = 3;

// TAO_IDL - Generated from
// c:\gamez\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:67

} // module Messaging

// TAO_IDL - Generated from
// c:\gamez\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:68


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// c:\gamez\ace_wrappers\tao\tao_idl\be\be_visitor_traits.cpp:62


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// c:\gamez\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1703


TAO_END_VERSIONED_NAMESPACE_DECL

#include /**/ "ace/post.h"

#endif /* ifndef */

